const anniversaryRouter = require("../routes/anniversary.js")
const clientExtraRouter = require("../routes/clientExtra.js");
const clientRouter = require("../routes/client.js");
const userRouter = require("../routes/user");
const anniversarySectorRouter = require("../routes/anniversarySector.js");
const anniversaryTypeRouter = require("../routes/anniversaryType.js");
const clientOldRouter = require("../routes/clientOld.js");
const companyExtraRouter = require("../routes/companyExtra.js");
const companySectorRouter = require("../routes/companySector.js");
const companyRouter = require("../routes/company.js");
const countryRouter = require("../routes/country.js");
const currentClientRouter = require("../routes/currentClient.js");
const currentStaffRouter = require("../routes/currentStaff.js");
const departmentRouter = require("../routes/department.js");
const familyTypeRouter = require("../routes/familyType.js");
const familyRouter = require("../routes/family.js");
const maritalStatusRouter = require("../routes/maritalStatus.js");
const paperRouter = require("../routes/paper.js");
const relationshipRouter = require("../routes/relationship.js");
const religionRouter = require("../routes/religion.js");
const saleRouter = require("../routes/sale.js");
const sectorRouter = require("../routes/sector.js");
const sexRouter = require("../routes/sex.js");
const staffLevelRouter = require("../routes/staffLevel.js");
const staffTypeRouter = require("../routes/staffType.js");
const staffRouter = require("../routes/staff.js");
const stateRouter = require("../routes/state.js");
const subSectorRouter = require("../routes/subSector.js");
const titleRouter = require("../routes/title.js");
const userRecordRouter = require("../routes/userRecord.js");
const loginRouter = require("../auth/login");

const setupRoutes = (app) => {
  app.use("/login", loginRouter);
  app.use("/anniversaries", anniversaryRouter);
  app.use("/clients", clientRouter);
  app.use("/clientExtras", clientExtraRouter);
  app.use("/users", userRouter);
  app.use("/anniversaryTypes", anniversaryTypeRouter);
  app.use("/anniversarySectors", anniversarySectorRouter);
  app.use("/oldClients", clientOldRouter);
  app.use("/companyExtras", companyExtraRouter);
  app.use("/companySectors", companySectorRouter);
  app.use("/companies", companyRouter);
  app.use("/countries", countryRouter);
  app.use("/currentClients", currentClientRouter);
  app.use("/currentStaffs", currentStaffRouter);
  app.use("/departments", departmentRouter);
  app.use("/familyTypes", familyTypeRouter);
  app.use("/families", familyRouter);
  app.use("/maritalStatuses", maritalStatusRouter);
  app.use("/papers", paperRouter);
  app.use("/relationships", relationshipRouter);
  app.use("/religions", religionRouter);
  app.use("/sales", saleRouter);
  app.use("/sectors", sectorRouter);
  app.use("/sexes", sexRouter);
  app.use("/staffLevels", staffLevelRouter);
  app.use("/staffTypes", staffTypeRouter);
  app.use("/staffs", staffRouter);
  app.use("/states", stateRouter);
  app.use("/subSectors", subSectorRouter);
  app.use("/titles", titleRouter);
  app.use("/userRecords", userRecordRouter);
};

module.exports = setupRoutes;
